In [1]:
import numpy as np

import wgpu
from wgpu.utils.compute import compute_with_buffers

In [2]:
def read_shader():
    return open("./qr.wgsl").read()

In [3]:
dtype_mapping = {
    np.int8: "b",
    np.int16: "h",
    np.int32: "i",
    np.float16: "e",
    np.float32: "f",
}

In [21]:
a = np.random.rand(5, 5).astype(np.float32)

In [22]:
a

array([[0.741042  , 0.92858607, 0.25000572, 0.9626224 , 0.32335472],
       [0.7971966 , 0.2737183 , 0.76534456, 0.4711124 , 0.5695381 ],
       [0.4018564 , 0.43775922, 0.9475955 , 0.83158445, 0.24838237],
       [0.31866008, 0.56678677, 0.6167728 , 0.29753003, 0.22332627],
       [0.586839  , 0.7422466 , 0.16003719, 0.774006  , 0.73952335]],
      dtype=float32)

In [24]:
a.ravel()[0:5]

array([0.741042  , 0.92858607, 0.25000572, 0.9626224 , 0.32335472],
      dtype=float32)

In [40]:
n = 1

# out_shape = a.shape
out_shape = (5,)
out = compute_with_buffers(
    input_arrays={0: a},
    output_arrays={1: (*out_shape, dtype_mapping[np.float32])},
    shader=read_shader(),
    n=n
)

shader_out = np.frombuffer(out[1], dtype=np.float32)
shader_out

array([1.5827565 , 1.3573935 , 1.4157279 , 0.97036016, 1.4376725 ],
      dtype=float32)

In [42]:
np.linalg.norm(a, ord=2, axis=1)

array([1.5827565 , 1.3573935 , 1.4157279 , 0.97036016, 1.4376725 ],
      dtype=float32)

In [41]:
shader_out == np.linalg.norm(a, ord=2, axis=1)

array([ True,  True,  True,  True,  True])